services:
  php:
    environment:
      APP_ENV: prod
      APP_DEBUG: 0
    volumes:
      - ./symfony:/var/www/symfony:ro
    restart: unless-stopped
    user: "${UID:-1000}:${GID:-1000}"

  nginx:
    ports:
      - "80:80"
    volumes:
      - ./symfony:/var/www/symfony:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
    user: "${UID:-1000}:${GID:-1000}"

  database:
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    restart: unless-stopped

  composer:
    user: "${UID:-1000}:${GID:-1000}"

volumes:
  db_data:
  redis_data: 