apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: symfony-prod

resources:
  - ../base
  - ingress.yaml

patches:
  - target:
      kind: Deployment
      name: symfony-php
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: europe-west1-docker.pkg.dev/trans-cosine-460409-m6/symfony-images/symfony-php:latest
  - target:
      kind: Deployment
      name: symfony-nginx
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: europe-west1-docker.pkg.dev/trans-cosine-460409-m6/symfony-images/symfony-nginx:latest

configMapGenerator:
  - name: symfony-config
    literals:
      - APP_ENV=prod
      - APP_DEBUG=false
      - APP_SECURE=true
      - SESSION_SECURE=true
      - COOKIE_SECURE=true 