    # Génération du fichier .env.docker.prod à partir des secrets GitHub
    # - name: Create .env.docker.prod
    #   run: |
    #     cat <<EOF > .env.docker.prod
    #     MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}
    #     MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}
    #     MYSQL_USER=${{ secrets.MYSQL_USER }}
    #     MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}
    #     APP_SECRET=${{ secrets.APP_SECRET }}
    #     JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}
    #     JWT_PASSPHRASE=${{ secrets.JWT_PASSPHRASE }}
    #     DATABASE_URL=mysql://${{ secrets.MYSQL_USER }}:${{ secrets.MYSQL_PASSWORD }}@database:3306/${{ secrets.MYSQL_DATABASE }}?serverVersion=8.0
    #     # Ajoute ici d'autres variables si besoin
    #     EOF

    # Exemple d'utilisation pour builder/pusher une image Docker (décommente si besoin)
    # - name: Build Docker image
    #   run: docker-compose --env-file .env.docker.prod build
    #
    # - name: Push Docker image
    #   run: docker-compose --env-file .env.docker.prod push