    # - name: Debug GitHub Context
    #   run: |
    #     echo "Repository: ${{ github.repository }}"
    #     echo "Actor: ${{ github.actor }}"
    #     echo "Ref: ${{ github.ref }}"
    #     echo "Event Name: ${{ github.event_name }}"

    # - name: Get OIDC Token
    #   id: oidc
    #   run: |
    #     TOKEN=$(curl -s -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
    #       -H "Accept: application/json" \
    #       -H "Content-Type: application/json" \
    #       "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=github-actions")
    #     echo "token=$TOKEN" >> $GITHUB_OUTPUT

    # - name: Decode Token
    #   run: |
    #     echo "${{ steps.oidc.outputs.token }}" | cut -d '.' -f2 | base64 -d | jq