apiVersion: apps/v1
kind: Deployment
metadata:
  name: symfony-php
spec:
  replicas: 1
  selector:
    matchLabels:
      app: symfony-php
  template:
    metadata:
      labels:
        app: symfony-php
    spec:
      containers:
      - name: php
        image: symfony-php:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
            ephemeral-storage: "500Mi"
          limits:
            memory: "512Mi"
            cpu: "500m"
            ephemeral-storage: "1Gi"
        env:
        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              name: symfony-config
              key: APP_ENV
        - name: APP_DEBUG
          valueFrom:
            configMapKeyRef:
              name: symfony-config
              key: APP_DEBUG
        - name: APP_SECURE
          valueFrom:
            configMapKeyRef:
              name: symfony-config
              key: APP_SECURE
        - name: SESSION_SECURE
          valueFrom:
            configMapKeyRef:
              name: symfony-config
              key: SESSION_SECURE
        - name: COOKIE_SECURE
          valueFrom:
            configMapKeyRef:
              name: symfony-config
              key: COOKIE_SECURE
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: symfony-db-credentials
              key: DATABASE_URL
        - name: APP_SECRET
          valueFrom:
            secretKeyRef:
              name: symfony-app-secret
              key: APP_SECRET
        - name: GOOGLE_MAPS_API_KEY
          valueFrom:
            secretKeyRef:
              name: google-maps-api-key
              key: GOOGLE_MAPS_API_KEY
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: symfony-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: symfony-nginx
  template:
    metadata:
      labels:
        app: symfony-nginx
    spec:
      containers:
      - name: nginx
        image: symfony-nginx:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
            ephemeral-storage: "100Mi"
          limits:
            memory: "128Mi"
            cpu: "100m"
            ephemeral-storage: "200Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: symfony-php
spec:
  selector:
    app: symfony-php
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: symfony-nginx
spec:
  selector:
    app: symfony-nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP 