apiVersion: apps/v1
kind: Deployment
metadata:
  name: symfony-php
spec:
  replicas: 1
  selector:
    matchLabels:
      app: symfony-php
  template:
    metadata:
      labels:
        app: symfony-php
    spec:
      serviceAccountName: sa-symfony-app
      initContainers:
      - name: init-chmod
        image: busybox
        command: ["sh", "-c", "chmod -R 777 /var/www/symfony"]
        volumeMounts:
        - name: symfony-code
          mountPath: /var/www/symfony
      containers:
      - name: php
        image: symfony-php:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 9000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: symfony-db-credentials
              key: DATABASE_URL
        - name: APP_SECRET
          valueFrom:
            secretKeyRef:
              name: symfony-app-secret
              key: APP_SECRET
        - name: GOOGLE_MAPS_API_KEY
          valueFrom:
            secretKeyRef:
              name: google-maps-api-key
              key: GOOGLE_MAPS_API_KEY
        volumeMounts:
        - name: symfony-code
          mountPath: /var/www/symfony
        - name: secrets-store
          mountPath: "/mnt/secrets"
          readOnly: true
      volumes:
      - name: symfony-code
        persistentVolumeClaim:
          claimName: symfony-code-pvc
      - name: secrets-store
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: symfony-secrets
      - name: nginx-config
        configMap:
          name: nginx-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: symfony-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: symfony-nginx
  template:
    metadata:
      labels:
        app: symfony-nginx
    spec:
      serviceAccountName: sa-symfony-app
      initContainers:
      - name: init-chmod
        image: busybox
        command: ["sh", "-c", "chmod -R 777 /var/www/symfony"]
        volumeMounts:
        - name: symfony-code
          mountPath: /var/www/symfony
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: symfony-code
          mountPath: /var/www/symfony
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
      volumes:
      - name: symfony-code
        persistentVolumeClaim:
          claimName: symfony-code-pvc
      - name: nginx-config
        configMap:
          name: nginx-config 