apiVersion: apps/v1
kind: Deployment
metadata:
  name: symfony-php
spec:
  replicas: 1
  selector:
    matchLabels:
      app: symfony-php
  template:
    metadata:
      labels:
        app: symfony-php
    spec:
      containers:
      - name: php
        image: symfony-php:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9000
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
            ephemeral-storage: "500Mi"
          limits:
            memory: "512Mi"
            cpu: "500m"
            ephemeral-storage: "1Gi"
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: symfony-db-credentials
              key: DATABASE_URL
        - name: APP_SECRET
          valueFrom:
            secretKeyRef:
              name: symfony-app-secret
              key: APP_SECRET
        - name: GOOGLE_MAPS_API_KEY
          valueFrom:
            secretKeyRef:
              name: google-maps-api-key
              key: GOOGLE_MAPS_API_KEY
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: symfony-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: symfony-nginx
  template:
    metadata:
      labels:
        app: symfony-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
            ephemeral-storage: "100Mi"
          limits:
            memory: "128Mi"
            cpu: "100m"
            ephemeral-storage: "200Mi"
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config 