apiVersion: v1
kind: PersistentVolume
metadata:
  name: symfony-code-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /Applications/MAMP/htdocs/mp/PHP_website/API_symfony/symfony 