apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: symfony-code-pvc
  namespace: symfony-prod
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
  storageClassName: standard-rwx