apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: symfony-secrets
spec:
  provider: gcp
  parameters:
    useSecretManager: "true"
    secrets:
      - resourceName: "projects/${PROJECT_ID}/secrets/symfony-db-credentials/versions/latest"
        path: "symfony-db-credentials"
      - resourceName: "projects/${PROJECT_ID}/secrets/symfony-app-secret/versions/latest"
        path: "symfony-app-secret" 