apiVersion: v1
kind: Secret
metadata:
  name: symfony-secrets
type: Opaque
data:
  # Les valeurs seront remplacées par les environnements spécifiques
  APP_SECRET: ${APP_SECRET}
  DATABASE_URL: ${DATABASE_URL} 
  GOOGLE_MAPS_API_KEY: ${GOOGLE_MAPS_API_KEY}