apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: symfony-secrets
spec:
  provider: gcp
  parameters:
    useSecretManager: "true"
    secrets:
      - resourceName: "projects/${PROJECT_ID}/secrets/symfony-db-credentials/versions/latest"
        path: "symfony-db-credentials"
      - resourceName: "projects/${PROJECT_ID}/secrets/symfony-app-secret/versions/latest"
        path: "symfony-app-secret" 
      - resourceName: "projects/${PROJECT_ID}/secrets/google-maps-api-key/versions/latest"
        path: "google-maps-api-key" 
    secretObjects:
    - secretName: google-maps-api-key
      type: Opaque
      data:
        - objectName: google-maps-api-key
          key: GOOGLE_MAPS_API_KEY