name: Deploy to GKE

on:
  push:
    branches: [ main ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
  GKE_ZONE: ${{ secrets.GKE_ZONE }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - uses: actions/checkout@v3

    - id: auth
      name: 'Authenticate to Google Cloud'
      uses: google-github-actions/auth@v2
      with:
        token_format: "id_token"
        workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
        service_account: ${{ secrets.GCP_SA_EMAIL }}

    - name: Dump OIDC Token
      run: |
        echo "${{ steps.auth.outputs.id_token }}" | cut -d '.' -f2 | base64 -d | jq

    # - name: 'Set up Cloud SDK'
    #   uses: 'google-github-actions/setup-gcloud@v1'

    # - name: 'Get GKE Credentials'
    #   run: |
    #     gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE --project $PROJECT_ID

    # - name: 'Deploy to GKE'
    #   run: |
    #     cd k8s/prod
    #     kustomize edit set image xandreges/symfony-php:prod=${{ github.sha }}
    #     kustomize build . | kubectl apply -f - 