name: Deploy to GKE

on:
  push:
    branches: [ main ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
  GKE_ZONE: ${{ secrets.GKE_ZONE }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - uses: actions/checkout@v3

    # - name: Debug GitHub Context
    #   run: |
    #     echo "Repository: ${{ github.repository }}"
    #     echo "Actor: ${{ github.actor }}"
    #     echo "Ref: ${{ github.ref }}"
    #     echo "Event Name: ${{ github.event_name }}"

    # - name: Get OIDC Token
    #   id: oidc
    #   run: |
    #     TOKEN=$(curl -s -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
    #       -H "Accept: application/json" \
    #       -H "Content-Type: application/json" \
    #       "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=github-actions")
    #     echo "token=$TOKEN" >> $GITHUB_OUTPUT

    # - name: Decode Token
    #   run: |
    #     echo "${{ steps.oidc.outputs.token }}" | cut -d '.' -f2 | base64 -d | jq

    - id: auth
      name: 'Authenticate to Google Cloud'
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
        service_account: ${{ secrets.GCP_SA_EMAIL }}

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    # Génération du fichier .env.docker.prod à partir des secrets GitHub
    # - name: Create .env.docker.prod
    #   run: |
    #     cat <<EOF > .env.docker.prod
    #     MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}
    #     MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}
    #     MYSQL_USER=${{ secrets.MYSQL_USER }}
    #     MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}
    #     APP_SECRET=${{ secrets.APP_SECRET }}
    #     JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}
    #     JWT_PASSPHRASE=${{ secrets.JWT_PASSPHRASE }}
    #     DATABASE_URL=mysql://${{ secrets.MYSQL_USER }}:${{ secrets.MYSQL_PASSWORD }}@database:3306/${{ secrets.MYSQL_DATABASE }}?serverVersion=8.0
    #     # Ajoute ici d'autres variables si besoin
    #     EOF

    # Exemple d'utilisation pour builder/pusher une image Docker (décommente si besoin)
    # - name: Build Docker image
    #   run: docker-compose --env-file .env.docker.prod build
    #
    # - name: Push Docker image
    #   run: docker-compose --env-file .env.docker.prod push

    - name: 'Get GKE Credentials'
      run: |
        gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE --project $PROJECT_ID

    - name: 'Deploy to GKE'
      run: |
        cd k8s/prod
        kustomize edit set image xandreges/symfony-php:prod=${{ github.sha }}
        kustomize build . | kubectl apply -f - 