name: Deploy to GKE

on:
  push:
    branches: [ main ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
  GKE_ZONE: ${{ secrets.GKE_ZONE }}

jobs:

  verify-auth:
    name: Verify Workload Identity Token
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Authenticate using Workload Identity Federation
        id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: 'id_token'
          id_token_audience: 'github-actions' # adapte si ton provider GCP attend autre chose
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}

      - name: Decode and inspect ID token
        run: |
          echo "${{ steps.auth.outputs.id_token }}" | cut -d "." -f2 | base64 -d | jq


  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - uses: actions/checkout@v3

    - id: auth
      name: 'Authenticate to Google Cloud'
      uses: google-github-actions/auth@v2
      continue-on-error: true
      with:
        token_format: 'id_token'
        id_token_audience: 'github-actions'
        workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
        service_account: ${{ secrets.GCP_SA_EMAIL }}

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: 'Get GKE Credentials'
      run: |
        gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE --project $PROJECT_ID

    - name: 'Deploy to GKE'
      run: |
        cd k8s/prod
        kustomize edit set image xandreges/symfony-php:prod=${{ github.sha }}
        kustomize build . | kubectl apply -f - 