name: Deploy to GKE

on:
  push:
    branches: [ main ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
  GKE_ZONE: ${{ secrets.GKE_ZONE }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - uses: actions/checkout@v3

    - name: Debug GitHub Context
      run: |
        echo "Repository: ${{ github.repository }}"
        echo "Actor: ${{ github.actor }}"
        echo "Ref: ${{ github.ref }}"
        echo "Event Name: ${{ github.event_name }}"

    - name: Get OIDC Token
      id: oidc
      uses: actions/github-script@v6
      with:
        script: |
          const token = await github.rest.actions.getActionsToken();
          console.log('Token:', token.data.token);
          return token.data.token;

    - name: Decode Token
      run: |
        echo "${{ steps.oidc.outputs.result }}" | cut -d '.' -f2 | base64 -d | jq

    # - name: 'Set up Cloud SDK'
    #   uses: 'google-github-actions/setup-gcloud@v1'

    # - name: 'Get GKE Credentials'
    #   run: |
    #     gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE --project $PROJECT_ID

    # - name: 'Deploy to GKE'
    #   run: |
    #     cd k8s/prod
    #     kustomize edit set image xandreges/symfony-php:prod=${{ github.sha }}
    #     kustomize build . | kubectl apply -f - 