name: Deploy to GKE

on:
  push:
    branches: [ main ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
  GKE_ZONE: ${{ secrets.GKE_ZONE }}
  IMAGE_NAME_PHP: europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/symfony-images/symfony-php
  IMAGE_NAME_NGINX: europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/symfony-images/symfony-nginx

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - uses: actions/checkout@v3

    - id: auth
      name: 'Authenticate to Google Cloud'
      uses: google-github-actions/auth@v2
      with:
        token_format: 'id_token'
        id_token_audience: 'github-actions'
        workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
        service_account: ${{ secrets.GCP_SA_EMAIL }}

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: 'Configure Docker for Artifact Registry'
      run: |
        gcloud auth configure-docker europe-west1-docker.pkg.dev --quiet
        gcloud config set container/use_application_default_credentials true

    - name: 'Debug Docker Configuration'
      run: |
        echo "=== Docker config ==="
        cat ~/.docker/config.json
        echo "=== GCloud auth list ==="
        gcloud auth list
        echo "=== Testing Artifact Registry access ==="
        gcloud auth print-access-token

    - name: 'Build and Push Docker Images'
      run: |
        gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin europe-west1-docker.pkg.dev
        docker build -t $IMAGE_NAME_PHP:${{ github.sha }} -f docker/php/Dockerfile .
        docker build -t $IMAGE_NAME_NGINX:${{ github.sha }} -f docker/nginx/Dockerfile docker/nginx/
        docker push $IMAGE_NAME_PHP:${{ github.sha }}
        docker push $IMAGE_NAME_NGINX:${{ github.sha }}

    - name: Install gke-gcloud-auth-plugin
      run: |
        gcloud components install gke-gcloud-auth-plugin --quiet
    
    - name: 'Get GKE Credentials'
      run: |
        gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE --project $PROJECT_ID

    - name: 'Deploy to GKE'
      run: |
        cd k8s/prod
        kubectl create namespace symfony-prod --dry-run=client -o yaml | kubectl apply -f -
        kustomize edit set image europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/symfony-images/symfony-php:latest=$IMAGE_NAME_PHP:${{ github.sha }}
        kustomize edit set image europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/symfony-images/symfony-nginx:latest=$IMAGE_NAME_NGINX:${{ github.sha }}
        kustomize build . | kubectl apply -f - 