name: Deploy to GKE

on:
  push:
    branches: [ main ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
  GKE_ZONE: ${{ secrets.GKE_ZONE }}
  REGISTRY: gcr.io
  IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/symfony-php

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - uses: actions/checkout@v3

    - id: auth
      name: 'Authenticate to Google Cloud'
      uses: google-github-actions/auth@v2
      with:
        token_format: 'id_token'
        id_token_audience: 'github-actions'
        workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
        service_account: ${{ secrets.GCP_SA_EMAIL }}

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: 'Configure Docker for GCR'
      run: |
        gcloud auth configure-docker $REGISTRY --quiet

    - name: 'Build and Push Docker Image'
      run: |
        docker build -t $IMAGE_NAME:${{ github.sha }} -f docker/php/Dockerfile .
        docker push $IMAGE_NAME:${{ github.sha }}

    - name: Install gke-gcloud-auth-plugin
      run: |
        gcloud components install gke-gcloud-auth-plugin --quiet
    
    - name: 'Get GKE Credentials'
      run: |
        gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE --project $PROJECT_ID

    - name: 'Deploy to GKE'
      run: |
        cd k8s/prod
        kubectl create namespace symfony-prod --dry-run=client -o yaml | kubectl apply -f -
        kustomize edit set image gcr.io/${{ secrets.GCP_PROJECT_ID }}/symfony-php:latest=$IMAGE_NAME:${{ github.sha }}
        kustomize build . | kubectl apply -f - 